FROM golang:1.26.3-alpine3.23 AS builder
RUN go install github.com/pressly/goose/v3/cmd/goose@v3.27.1

FROM alpine:3.23 AS final
# Пакет libpq для postgresql.
RUN apk add --no-cache ca-certificates libpq 
COPY --from=builder /go/bin/goose /usr/local/bin/goose

WORKDIR /migrations

ENTRYPOINT [ "goose" ]